name: Tests for jasmin-ref implementation

on:
  workflow_dispatch:
  push:
    branches:
      - main
  pull_request:

jobs:
  build:
    runs-on: [self-hosted, linux, X64, amd64-main]
    strategy:
      matrix:
        directory:
          - fips202/shake256_inc/
          - thash
    steps:
      - uses: actions/checkout@v1
      - name: Run tests
        run:
          JASMIN=$(which_jasminc) make -C test/${{ matrix.directory }} run
